#config_version=6


hardware:
    platform: fast

mpf:
    report_crashes: never

fast:
  net:
    debug: false      # change to true to see full NET serial communication in the log. Search for `[NET]`
    # port: /dev/cu.usbmodem14601
    controller: neuron
    io_loop: 
            cab:
                model: FP-CAB-0001
                order: 1
            top1616:
                model: FP-I/O-1616
                order: 2
            bottom3208:
                model: FP-I/O-3208
                order: 3
    port: auto
    baud: 921600
    debug: false
    watchdog: 1s
    default_quick_debounce_open: 2ms
    default_quick_debounce_close: 2ms
    default_normal_debounce_open: 4ms
    default_normal_debounce_close: 4ms

  exp:
    debug: false      # change to true to see full EXP serial communication in the log. Search for `[EXP]`
    # port: /dev/cu.usbmodem14603
    boards:
      neuron:
        model: FP-EXP-2000
        breakouts:
          - port: 1
            model: FP-PWR-0007

switches:
  ## Flipper Cabinet Buttons
  s_left_flipper:
    number: cab-999
    tags: left_flipper
  s_right_flipper:
    number: cab-999
    tags: right_flipper

  s_start:
    number: cab-999
    tags: start

  ## Flipper EOS Switches
  s_left_flipper_eos: # End of Stroke
    number: bottom3208-25
  s_right_flipper_eos: # End of Stroke
    number: bottom3208-24

    # Bottom Third Switches. Left to Right.
  s_outlane_left:
    number: bottom3208-19
    tags: left_outlane, playfield_active
  s_inlane_left_outer:
    number: bottom3208-18
    tags: playfield_active
  s_inlane_left_inner:
    number: bottom3208-17
    tags: playfield_active
  s_inlane_right_inner:
    number: bottom3208-27
    tags: playfield_active
  s_inlane_right_outer:
    number: bottom3208-28
    tags: playfield_active
  s_outlane_right:
    number: bottom3208-29
    tags: playfield_active
  
  s_sling_left:
    number: bottom3208-16 ## To check
  s_sling_right:
    number: bottom3208-26

  #Trough Switches (x8)
  s_trough1: # Opto Switch (Not yet installed)
    number: bottom3208-999
    type: NC
  s_trough2:
    number: bottom3208-0
  s_trough3:
    number: bottom3208-1
  s_trough4:
    number: bottom3208-3
  s_trough5:
    number: bottom3208-2
  s_trough6:
    number: bottom3208-4
  s_trough7:
    number: bottom3208-5
  s_trough8:
    number: bottom3208-6
  s_trough_jam:
    number: bottom3208-999 # Not yet installed.
    type: NC

  # plunger lane
  s_plunger_lane:
    number: bottom3208-999 # Not yet installed.
  
  # EMP Pop Bumper Area Switches
  s_emp_pop:
    number: bottom3208-14
    debounce: quick
  s_emp_trigger:
    number: bottom3208-13
    tags: playfield_active
  s_emp_target_1:
    number: bottom3208-9
    tags: playfield_active
  s_emp_target_2:
    number: bottom3208-10
    tags: playfield_active
  s_emp_target_3:
    number: bottom3208-11
    tags: playfield_active
  s_emp_target_4:
    number: bottom3208-12
    tags: playfield_active
  s_kickback_target:
    number: bottom3208-8
    tags: playfield_active

  # Ammo Target
  s_ammo_target:
    number: bottom3208-20
    tags: playfield_active
  s_ammo_rollover:
    number: bottom3208-21
    tags: playfield_active


coils:
  # Bottom Third Coils.
  c_auto_plunge:
    number: bottom3208-0
  c_trough_eject:
    number: bottom3208-1
    default_pulse_ms: 20
  c_flipper_left_hold:
    number: bottom3208-2
    allow_enable: true # Allows the flipper coil power to be held (failsafe)
  c_flipper_left_main:
    number: bottom3208-3
    default_pulse_ms: 10
  c_flipper_right_hold:
    number: bottom3208-4
    allow_enable: true # Allows the flipper coil power to be held (failsafe)
  c_flipper_right_main:
    number: bottom3208-5
    default_pulse_ms: 10
  c_sling_right:
    number: bottom3208-6
    default_pulse_ms: 20
    platform_settings:
      recycle_ms: 40
  c_sling_left:
    number: bottom3208-7
      default_pulse_ms: 20
    platform_settings:
      recycle_ms: 40
  
  # Middle Playfield Coils (in EMP)
  c_emp_pop:
    number: top1616-999 # Not yet installed.
    default_pulse_ms: 20
    platform_settings:
      recycle_ms: 40

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger

virtual_platform_start_active_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough7


flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    eos_switch: s_left_flipper_eos
    use_eos: true
    # enable_events: machine_reset_phase_3 # Allows the flippers to work before a ball is started
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    eos_switch: s_right_flipper_eos
    use_eos: true
    # enable_events: machine_reset_phase_3 # Allows the flippers to work before a ball is started

autofire_coils:
  c_sling_left:
    switch: s_sling_left
    coil: c_sling_left
  c_sling_right:
    switch: s_sling_right
    coil: c_sling_right

ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough7, s_trough8 s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam # Opto switch to detect a jam in the trough
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    eject_timeouts: 3s
  bd_plunger:
    ball_switches: s_plunger
    mechanical_eject: true
    eject_timeouts: 5s

displays:
  window:
    width: 800
    height: 600

slides:
  welcome_slide:
    widgets:
      - type: text
        text: PINBALL!
        font_size: 50
        color: red
      - type: rectangle
        width: 240
        height: 60
  attract_started:
    widgets:
      - text: ATTRACT MODE
        type: text
slide_player:
  init_done: welcome_slide
  mode_attract_started: attract_started
  ball_started:
    widgets:
      type: text
      text: PLAYER (number) BALL (ball)


keyboard:
  s:
    switch: s_start
  q:
    switch: s_right_inlane
  1:
    switch: s_trough1
    toggle: true
  2:
    switch: s_trough2
    toggle: true
  3:
    switch: s_trough3
    toggle: true
  4:
    switch: s_trough4
    toggle: true
  5:
    switch: s_trough5
    toggle: true
  6:
    switch: s_trough6
    toggle: true
  7:
    switch: s_trough7
    toggle: true
  p:
    switch: s_plunger
    toggle: true