#config_version=6


hardware:
    platform: fast

mpf:
    report_crashes: never

fast:
  net:
    debug: false      # change to true to see full NET serial communication in the log. Search for `[NET]`
    controller: neuron
    io_loop: 
      top1616:
          model: FP-I/O-1616
          order: 1
      bottom3208:
          model: FP-I/O-3208
          order: 2


switches:

  ## Flipper EOS Switches
  s_left_flipper_eos: # End of Stroke
    number: bottom3208-25
  s_right_flipper_eos: # End of Stroke
    number: bottom3208-24

    # Bottom Third Switches. Left to Right.
  s_outlane_left:
    number: bottom3208-19

  s_outlane_right:
    number: bottom3208-29


coils:
  # Bottom Third Coils.
  c_auto_plunge:
    number: bottom3208-0
  c_trough_eject:
    number: bottom3208-1
    default_pulse_ms: 20
  c_flipper_left_hold:
    number: bottom3208-2
    allow_enable: true # Allows the flipper coil power to be held (failsafe)
  c_flipper_left_main:
    number: bottom3208-3
  c_flipper_right_hold:
    number: bottom3208-4
    allow_enable: true # Allows the flipper coil power to be held (failsafe)
  c_flipper_right_main:
    number: bottom3208-5
    default_pulse_ms: 20

playfields:
  playfield:
    tags: default
    default_source_device: None

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_outlane_left
    enable_events: machine_reset_phase_3, mode_attract_started # Allows the flippers to work before a ball is started
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_outlane_right
    enable_events: machine_reset_phase_3, mode_attract_started # Allows the flippers to work before a ball is started
