#config_version=6

# To use this file with your own hardware:
# Connect the Neuron via USB, plug in some LEDs
# cd into the fast-mpf-starter-configs folder
# Then run via `mpf -btc neuron-0081`  The first LED of each port should light up in red, green, blue, white cycling on 1s intervals

hardware:
    platform: fast

mpf:
    report_crashes: never

fast:
  net:
    debug: false      # change to true to see full NET serial communication in the log. Search for `[NET]`
    controller: neuron

  exp:
    debug: false      # change to true to see full EXP serial communication in the log. Search for `[EXP]`
    boards:
      neuron:
        model: FP-EXP-2000
      '0081':
        model: FP-EXP-0081

lights:
  led1-1:               # These names are arbitrary. Make them whatever you want
    number: neuron-1-1  # Neuron LED Port 1, first LED in the chain
  led2-1:
    number: neuron-2-1  # Neuron LED Port 2, first LED in the chain
  led3-1:
    number: neuron-3-1  # Neuron LED Port 3, first LED in the chain
  led4-1:
    number: neuron-4-1  # Neuron LED Port 4, first LED in the chain
  81-led-1:
    number: 0081-1-1      # EXP Board 0081 (based on the "0081" name in the exp: section above), LED Port 1, first LED in the chain
  81-led-2:
    number: 0081-2-1      # EXP Board 0081, LED Port 2, first LED in the chain
  81-led-3:
    number: 0081-3-1      # EXP Board 0081, LED Port 3, first LED in the chain
  81-led-4:
    number: 0081-4-1      # EXP Board 0081, LED Port 4, first LED in the chain
  81-led-5:
    number: 0081-5-1      # EXP Board 0081, LED Port 5, first LED in the chain
  81-led-6:
    number: 0081-6-1      # EXP Board 0081, LED Port 6, first LED in the chain
  81-led-7:
    number: 0081-7-1      # EXP Board 0081, LED Port 7, first LED in the chain
  81-led-8:
    number: 0081-8-1      # EXP Board 0081, LED Port 8, first LED in the chain

show_player:
  mode_attract_started: startup

shows:
  startup:
    - time: 0
      lights:
        led1-1:
          color: red
        led2-1:
          color: green
        led3-1:
          color: blue
        led4-1:
          color: white
        81-led-1:
          color: red
        81-led-2:
          color: green
        81-led-3:
          color: blue
        81-led-4:
          color: white
        81-led-5:
          color: red
        81-led-6:
          color: green
        81-led-7:
          color: blue
        81-led-8:
          color: white
    - time: '+1'
      lights:
        led1-1:
          color: green
        led2-1:
          color: blue
        led3-1:
          color: white
        led4-1:
          color: red
        81-led-1:
          color: green
        81-led-2:
          color: blue
        81-led-3:
          color: white
        81-led-4:
          color: red
        81-led-5:
          color: green
        81-led-6:
          color: blue
        81-led-7:
          color: white
        81-led-8:
          color: red
    - time: '+1'
      lights:
        led1-1:
          color: blue
        led2-1:
          color: white
        led3-1:
          color: red
        led4-1:
          color: green
        81-led-1:
          color: blue
        81-led-2:
          color: white
        81-led-3:
          color: red
        81-led-4:
          color: green
        81-led-5:
          color: blue
        81-led-6:
          color: white
        81-led-7:
          color: red
        81-led-8:
          color: green
    - time: '+1'
      lights:
        led1-1:
          color: white
        led2-1:
          color: red
        led3-1:
          color: green
        led4-1:
          color: blue
        81-led-1:
          color: white
        81-led-2:
          color: red
        81-led-3:
          color: green
        81-led-4:
          color: blue
        81-led-5:
          color: white
        81-led-6:
          color: red
        81-led-7:
          color: green
        81-led-8:
          color: blue
